name: Update Outdated and Completed Homeworks

on:
    schedule:
        - cron: '0 0 * * *'


jobs:
    update_homework:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python3.9
              uses: actions/setup-python@v4
              with:
                python-version: '3.9'
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install notion-client
            
            - name: Run Python script
              env: 
                NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
                DATABASE_ID: ${{ secrets.DATABASE_ID }}
              run: |
                python main.py
