name: Update Expried and Completed Homeworks

env: 
  NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
  DATABASE_ID: ${{ secrets.DATABASE_ID }}

on:
    workflow_dispatch:  # workflow_dispatch イベントを追加
      inputs:  # 入力を定義
        database_id_input:  # 入力の名前 (任意)
          description: 'Database ID (for testing)' # 入力の説明 (UIに表示される)
          required: false # 必須入力ではない (省略可能)
          default: DATABASE_ID # デフォルト値 (Secrets の DATABASE_ID を使用)

    schedule:
        - cron: '0 15 * * *' # UTCだから-9してJSTの0:00に合わせています。


jobs:
    update_homework:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python3.9
              uses: actions/setup-python@v4
              with:
                python-version: '3.9'
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install notion-client
            
            - name: Run Python script
              env: 
                NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
                DATABASE_ID: ${{ secrets.DATABASE_ID }}
              run: |
                python main.py
